### ISSUE TITLE
Split Modules

### ISSUE THREAD

**Issue by curran** [pachamaltese/d3po#26]
Part of #15, the goal here is to split up large JS files ( > 500 lines) into smaller modules.

 * [X] viz/helpers/ui/legend.js https://github.com/pachamaltese/d3po/pull/31
 * [x] viz/types/helpers/graph/includes/svg.js
 * [ ] viz/helpers/shapes/draw.js
 * [ ] viz/helpers/shapes/edges.js
 * [ ] viz/helpers/ui/timeline.js
 * [ ] tooltip/create.js
 * [ ] geom/largestrectangle.js
 * [ ] viz/types/helpers/graph/includes/plot.js
 * [ ] viz/types/rings.js

**Comment by curran** [comment]
@pachamaltese Regarding splitting modules, I'm thinking to tackle the largest files only and leave the rest. There are 9 files that are over 500 lines of code. I think limiting the scope of this task to just these files is a good idea. Thoughts?

```
  1     751 ./src/viz/helpers/ui/legend.js
  2     748 ./src/viz/types/helpers/graph/includes/svg.js
  3     738 ./src/viz/helpers/shapes/draw.js
  4     688 ./src/viz/helpers/shapes/edges.js
  5     664 ./src/viz/helpers/ui/timeline.js
  6     601 ./src/tooltip/create.js
  7     558 ./src/geom/largestrectangle.js
  8     556 ./src/viz/types/helpers/graph/includes/plot.js
  9     501 ./src/viz/types/rings.js
```

FWIW the command to get this list is `find . -type f -exec wc -l {} + | sort -rn | head`

**Comment by pachadotdev** [comment]
@curran I agree. I'll post an idea in regards to `find`

**Comment by curran** [comment]
@pachamaltese I'm noticing that there are no examples that use the legend component, so if I refactor that file there is no way to verify whether it breaks something or not. How would you like me to proceed?

**Comment by pachadotdev** [comment]
Hmmm. Can legend be removed without breaking something? I have examples for
footers and headers.

**Comment by pachadotdev** [comment]
Or give me a time to look into an old external hdd

**Comment by curran** [comment]
I can remove the legend module completely without breaking any of the examples that are there with HTML.

![image](https://user-images.githubusercontent.com/68416/72898182-9a5e4e00-3d49-11ea-9d1d-4aed9a4520d9.png)

I wonder, do you have any R-based examples that use the legend that could be easily ported to JavaScript?

I'm happy to just remove the legend component if you don't want the library to be able to make legends.

**Comment by pachadotdev** [comment]
thanks Curran, right now I don't see a clear example where to use legends

right now this has title, subtitle and footer
[image: image.png]

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by pachadotdev** [comment]
I think legends are important... let me think a bit

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by pachadotdev** [comment]
@curran I added  a very stupid example here https://github.com/pachamaltese/d3po/blob/master/dev/treemap_with_legend.html

I shall port legends after remembering that 3 yrs ago I used those a lot

![image](https://user-images.githubusercontent.com/10091065/72899611-20a47100-3d05-11ea-8ff4-028d7a593930.png)

**Comment by curran** [comment]
Excellent! Thank you for adding that.

**Comment by curran** [comment]
Legend refactoring ready for review https://github.com/pachamaltese/d3po/pull/31
