### ISSUE TITLE
Are color random and scale module doing what is expected?

### ISSUE THREAD

**Issue by severo** [pachamaltese/d3po#7]
See https://github.com/pachamaltese/d3po/blob/master/javascript/src/color/random.js and https://github.com/pachamaltese/d3po/blob/master/javascript/src/color/scale.js

Reading the code, the expected behavior seems to be:

```
// defined as: d3.scale.ordinal().range(["#bf3251", "#5c57d9", "#d6c650", "#406662", "#872a41", "#1c26b3", "#d05555", "#549e95", "#993f7b", "#dc8e7a", "#ede788", "#7485aa", "#4d6fd0", "#635b56", "#7454a6", "#a8c380", "#8abdb6", "#74c0e2", "#bcd8af", "#a1aafb", "#a17cb0", "#d1a1bc"]);
var defaultScale = require("./scale.js");

console.log(defaultScale(3))
// expected: "#406662", because it's the fourth color in the array (idx=3)
// actual: "#bf3251", because it's the first call to the scale and the argument (3) is not in the scale domain
```

But it's not, because no domain is defined for the ordinal scale. The actual behavior is that every call to the `defaultScale` function will return the following value in the range, and the argument is ignored since the domain is empty (in reality, every new argument is added to the domain, and a further call with the same argument will return the same value):

```
// defined as: d3.scale.ordinal().range(["#bf3251", "#5c57d9", "#d6c650", "#406662", "#872a41", "#1c26b3", "#d05555", "#549e95", "#993f7b", "#dc8e7a", "#ede788", "#7485aa", "#4d6fd0", "#635b56", "#7454a6", "#a8c380", "#8abdb6", "#74c0e2", "#bcd8af", "#a1aafb", "#a17cb0", "#d1a1bc"]);
var defaultScale = require("./scale.js");

console.log(defaultScale(235))
// returns the first value: #bf3251

console.log(defaultScale("string"))
// returns the second value: #5c57d9

console.log(defaultScale(0))
// returns the third value: #d6c650

console.log(defaultScale(235))
// returns the first value again: #bf3251, because 235 has been added to the domain
```

Thus, the values returned by https://github.com/pachamaltese/d3po/blob/master/javascript/src/color/random.js are not random at all.

**Comment by pachadotdev** [comment]
Oh no, I don't want the colors to be random. Actually, that palette was my
modification provided it had different colors I didn't like.

**Comment by severo** [comment]
Yes, I understand that the set of colors has been chosen carefully and is not random.

I was referring to https://github.com/pachamaltese/d3po/blob/master/javascript/src/color/random.js -> it seems that the expected behavior of that function is to pick a color randomly from that set of colors you chose. But it doesn't (see the reason in the issue above).

Or did I miss something?

**Comment by pachadotdev** [comment]
Random.js shall be removed then

**Comment by severo** [comment]
I think the problem could be fixed by replacing:

```javascript
module.exports = d3.scaleOrdinal().range(["#bf3251", "#5c57d9", ..., "#d1a1bc"]);
```

by

```javascript
module.exports = d3.scaleOrdinal().range(["#bf3251", "#5c57d9", ..., "#d1a1bc"])
    .domain(d3.range(0,22));
```

And all would work as expected, random.js included.

**Comment by pachadotdev** [comment]
Sure!

**Comment by severo** [comment]
OK, I will change this (after migrating to d3@5).
